function write2xlsx(records,filename)
theTable = table(records(:,2),records(:,3),records(:,4),records(:,5),...
    records(:,6),...
    'VariableNames',{'f0','w','\beta','feva','iteration'});
writetable(theTable,filename);